[project]
name = "trade-executor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.7",
    "alpaca-py>=0.42.2",
    "pika>=1.3.2",
]
