services:
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - trading_net

  db:
    # image: timescale/timescaledb:latest-pg17
    image: postgres:17-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trading_db
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d trading_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trading_net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trading_net

  finance_worker:
    build:
      context: ../services/finance_worker
      dockerfile: Dockerfile
    container_name: finance_worker
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - RAW_QUEUE_NAME=data.finance
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET=${ALPACA_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trading_net

  social_worker:
    build:
      context: ../services/social_worker
      dockerfile: Dockerfile
    container_name: social_worker
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trading_net

  ml_processor:
    build:
      context: ../services/ml_processor
      dockerfile: Dockerfile
    container_name: ml_processor
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trading_net

  trade_executor:
    build:
      context: ../services/trade_executor
      dockerfile: Dockerfile
    container_name: trade_executor
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      # FIXME: remove these secrets
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET=${ALPACA_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trading_net

  api_gateway:
    build:
      context: ../services/api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - '8000:8000'
    depends_on:
      redis: 
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - trading_net

  dashboard:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
      args:
        - VITE_API_GATEWAY_HTTP_BASE=http://localhost:8000
        - VITE_API_GATEWAY_WS=ws://localhost:8000/ws
    container_name: dashboard
    ports:
      - "3000:80"
    depends_on:
      api_gateway:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trading_net

networks:
  trading_net:
    driver: bridge

volumes:
  rabbitmq_data:
  redis_data:
  timescale_data:
