x-servcie-path: &service-path ../services

services:
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - trading_net

  finance_worker:
    build:
      context: *service-path
      dockerfile: finance_worker/Dockerfile
    container_name: finance_worker
    env_file: .env
    depends_on:
      - rabbitmq
    networks:
      - trading_net

  social_worker:
    build:
      context: *service-path
      dockerfile: social_worker/Dockerfile
    container_name: social_worker
    env_file: .env
    depends_on:
      - rabbitmq
    networks:
      - trading_net

  ml_processor:
    build:
      context: *service-path
      dockerfile: ml_processor/Dockerfile
    container_name: ml_processor
    env_file: .env
    depends_on:
      - rabbitmq
    networks:
      - trading_net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trading_net

  db:
    image: timescale/timescaledb:latest-pg17
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - trading_net

  trade_executor:
    build:
      context: *service-path
      dockerfile: trade_executor/Dockerfile
    container_name: trade_executor
    env_file: .env
    depends_on:
      - rabbitmq
      - db
    networks:
      - trading_net

  # dashboard:
  #   build:
  #     context: *service-path
  #     dockerfile: dashboard/Dockerfile
  #   container_name: dashboard
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - redis
  #     - db
  #   networks:
  #     - trading_net

networks:
  trading_net:
    driver: bridge

volumes:
  rabbitmq_data:
  redis_data:
  timescale_data:
